---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: marghe-shop-final
    app.kubernetes.io/name: marghe-shop-final
    rht-gitops.com/janus-argocd: marghe-shop-final
  name: storeuser-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    backstage.io/kubernetes-id: marghe-shop-final
    app.kubernetes.io/name: marghe-shop-final
    rht-gitops.com/janus-argocd: marghe-shop-final
  name: storeuseradmin-sa
