---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: marghe-shop-final-scc-storeuser
  labels:
    backstage.io/kubernetes-id: marghe-shop-final
    app.kubernetes.io/name: marghe-shop-final
    rht-gitops.com/janus-argocd: marghe-shop-final
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 10001
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:marghe-shop:storeuser-sa
---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: marghe-shop-final-scc-storeuseradmin
  annotations:
    backstage.io/kubernetes-id: marghe-shop-final
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowHostPorts: false
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:marghe-shop:storeuseradmin-sa
